### ISSUE TITLE
Muscle Cost Functions

### ISSUE THREAD

**Issue by FaSchimmelpfennig** [anmuller/CusToM#10]
Dear Sir and Madam,
I am working on my thesis. It deals with different types of cost functions of muscles. I have two questions.

1. Among my thesis I am applying different cost function to the ellbow modell of Rasmussen (DOI:10.1016/S0021-9290(00)00191-3).
I have used the cost functions which are implemented in the CusToM-toolbox. But the results (first picture) are for higher power of the polynomial cost function not the same as the ones of Rasmussen (second picture). 

![CusToM](https://user-images.githubusercontent.com/71722281/93916329-a865d380-fd09-11ea-8fa4-0155081d8c12.PNG)
![Rasmussen](https://user-images.githubusercontent.com/71722281/93916344-adc31e00-fd09-11ea-841b-fcab3bb31288.PNG)

I have read in different journal papers that with increasing power of the polynomial cost function the results should approach the results of the min/max cost function. 
Do you have an idea what i did wrong ?
This is my code:
```
clearvars

%% Inputs
MuscleList = ['1' '2' '3'];                         % muscle names
Fmax = [1450;1200;1000];                     % maximal muscle forces
beq(3,:) = 0:10:230;                                % sum of external moments around ellbowjoint
dP = [2 3 5 10 100];                               % various degrees of polynom
nr_muscles = length(MuscleList);
Aeq = zeros(3,nr_muscles);
Aeq(3,:) = [.1 .05 .02];                            % lever arms of muscles around ellbow joint
[Fmin,F0] = deal(zeros(3,1));

%% Parameters
nr_moments = size(beq,2);
nr_polynoms = length(dP);
F_mm = zeros(nr_muscles, nr_moments);

% options = optimoptions(@fmincon,'Algorithm','sqp','Display','off','GradObj','off','GradConstr','off','TolFun',1e-6);
% options = optimoptions(@fmincon,'Algorithm','sqp','Display','off','GradObj','off','GradConstr','off','TolFun',1e-9,'MaxFunEvals',20000);
options = optimoptions(@fmincon,'Algorithm','sqp','Display','off','GradObj','off','GradConstr','off','TolFun',1e-9,'MaxFunEvals',100000,'TolX',1e-9,'StepTolerance',1e-15,'FunctionTolerance',1e-10,'MaxIterations',5000);

%% Calculation
% Muscle Recruitment
for i = 1:nr_moments
    
    for j = 1:nr_polynoms
        % Polynomial [Pedotti et al. 1978, Herzog 1978, Happee 1994]
        disp(['Power' num2str(dP(j)) ' - Moment ' num2str(beq(3,i))])
        cost_function_pol_max = @(F) sum((F./Fmax).^(dP(j)));
        F_pol.(['Power' num2str(dP(j))])(:,i) = ...
            fmincon(cost_function_pol_max,F0,[],[],Aeq,beq(:,i),Fmin,Fmax,[],options);
    end
    
    % Min/Max [Rasmussen et al. 2001, Olhoff 1989]
    disp(['Min/Max - Moment ' num2str(beq(3,i))])
    cost_function = @(F) F(1);
    Aeqbis = [zeros(size(Aeq,1),1) Aeq];
    F_inter = fmincon(cost_function,[1;F0],[],[],Aeqbis,beq(:,i),[0;Fmin],[Inf;Fmax],@(F) constraint_minmax(F,Fmax));
    F_mm(:,i) = F_inter(2:end,:);
end

%% Plot
figure('color','w','Position',[0,0,750,830])
tiledlayout(3,2);
xTicks = 0:50:250;
yTicks_F = 0:200:1600;
for j = 1:nr_polynoms
    F_tmp = F_pol.(['Power' num2str(dP(j))]);
    ax = nexttile;
    plot(ax, beq(3,:),F_tmp(1,:),'g--',beq(3,:),F_tmp(2,:),'b--',beq(3,:),F_tmp(3,:),'r--')
    title(ax, ['Power ' num2str(dP(j))])
    xlabel(ax, 'Moment [Nm]')
    ylabel(ax, 'Muscle forces [N]')
    set(ax,'xtick',xTicks,'ytick',yTicks_F,'xlim',[0,250],'ylim',[0,1600])
    grid(ax, 'on')
    if j == 1
        legend(ax, {'f^{(M)}_1','f^{(M)}_2','f^{(M)}_3'},'Location','northwest')
    end
end

ax = nexttile;
F_tmp = F_pol.('Power100');
lineH = plot(ax, ...
    beq(3,:),F_tmp(1,:),'g--',beq(3,:),F_tmp(2,:),'b--',beq(3,:),F_tmp(3,:),'r--',...
    beq(3,:),F_mm(1,:),'g-',beq(3,:),F_mm(2,:),'b-',beq(3,:),F_mm(3,:),'r-');
title(ax, 'Min/Max')
xlabel(ax, 'Moment [Nm]')
ylabel(ax, 'Muscle forces [N]')
legend(ax, lineH([1,4]),{'f^{(M)}_1 Power 100','f^{(M)}_1 Min/Max'},'Location','northwest')
set(ax, 'xtick',xTicks,'ytick',yTicks_F,'xlim',[0,250],'ylim',[0,1600])
grid(ax, 'on')


function [g,h] = constraint_minmax(F,Fmax)
% Constraint for min/max optimization
g = F(2:end)./Fmax-F(1);
h = [];
end
```
2. My second topic deals with the different muscles.  I would like to know how you chose the muscles which are active in your model or are you calculating with all the muscles ? How did you calculate the maximal strength of the muscles or from which source did you get these values ?

Thank you in advance. 
Best regards

**Comment by modenaxe** [comment]
Hi @FaSchimmelpfennig, 
interesting problem and I will leave the developers to comment on the CusToM aspects. From a general point of view, keep in mind what the paper you are trying to replicate says in the Discussion session:
>From the algorithmic point of view, the polynomial and soft saturation criteria have the clear drawback that a high power tends to create numerical difficulties and requires sophisticated optimization algorithms.


I think the problem is numerical and due to dealing with a sum of very small quantities (activations close to zero powered).

**Comment by cpontonn** [comment]
Hi @FaSchimmelpfennig . First of all thanks to @modenaxe who answered quite clearly to the issue: results seems irrelevant for high powers and low levels of activation. A solution may be to adapt the maximal isometric force of the muscles to keep a minimal level of activation along the simulation. 

For the second part of your issue, all muscles included in a given muscle set (associated to the osteoartcular model) are de facto active in a simulation. You can consider adding a 'is active' muscle  field if it is needed in your simulation, but it will ask for a bit of development.  Maximal isometric forces or strentgh for lower limb muscles are mostly issued from:

Horsman, M. K., Koopman, H. F., van der Helm, F. C., Prosé, L. P., & Veeger, H. E. J. (2007). Morphological muscle and joint parameters for musculoskeletal modelling of the lower extremity. Clinical biomechanics, 22(2), 239-247.

and all the derivatives (twente model)

upper limb muscles are mostly issued from:

Holzbaur, Katherine RS, Wendy M. Murray, and Scott L. Delp. "A model of the upper extremity for simulating musculoskeletal surgery and analyzing neuromuscular control." Annals of biomedical engineering 33.6 (2005): 829-840.
