### ISSUE TITLE
Utilisation de custom pour des données .mat

### ISSUE THREAD

**Issue by Biotry** [anmuller/CusToM#11]
Bonjour,
J'essaie d'utiliser le programme custom à partir d'un fichier .txt
Je l'ai d'abord ouvert en .mat et modifier pour qu'il soit de la même forme que les ExperimentalData des tutos (structure avec FirstFrame, LastFrame, Time, Markerpositions). Puis j'ouvre mon ExperimentData.mat dans Analysis en choisissant comme parameters MatProcessed.Data et quand je lance et j'obtiens le message d'erreur suivant :

"_Error using filt_data>filtrage_data (line 28)
Subscripting into a table using one subscript (as in t(i)) is not supported. Specify a
row subscript and a variable subscript, as in t(rows,vars). To select variables, use
t(:,i) or for one variable t.(i). To select rows, use t(i,:).

Error in filt_data (line 21)
    data(:,i)=filtrage_data(data(:,i),f,f_mocap);

Error in Get_real_markers (line 31)
    	real_markers(i).position =
        filt_data(real_markers(i).position_c3d,AnalysisParameters.General.FilterCutOff,f);_
"
En fait je n'ai aucune variable comme list_markers ou real_markers, j'aimerais à partir de l'Experimental.Data que j'ai développé utiliser les fonctionnalités de Custom. Donc est ce que c'est possible ? 
Est-il préférable que je passe absolument par un fichier .c3d ?(je n'ai pas trouvé de convertisseur de .txt ou .mat en .c3d)
Ou bien je dois programmer différemment mon .mat (et si oui avez vous un modèle)

**Comment by anmuller** [comment]
Bonjour,

Merci de l'intérêt que vous portez à CusToM.

Deux solutions s'offrent à vous pour utiliser CusToM à partir de données contenues dans un fichier .txt (ou un autre format type .mat).

1) Convertir vos données en un fichier c3d pour ensuite utiliser les outils existants de CusToM. Cela se fait assez bien avec btk : http://biomechanical-toolkit.github.io/docs/Wrapping/Matlab/annotated.html
Une fois le c3d généré, vous pouvez alors utiliser les fichiers d'import de CusToM.

2) Créer une fonction Matlab d'import qui sera spécifique à votre format de données en .txt. Cette devra être placé dans le dossier Functions/DataImport/InputDataImport pour ensuite être directement sélectionné dans l'interface graphique.
Cette nouvelle fonction doit contenir les mêmes entrées/sorties que la fonction C3dProcessedData.

**Comment by Biotry** [comment]
> Bonjour,
> 
> Merci de l'intérêt que vous portez à CusToM.
> 
> Deux solutions s'offrent à vous pour utiliser CusToM à partir de données contenues dans un fichier .txt (ou un autre format type .mat).
> 
> 1. Convertir vos données en un fichier c3d pour ensuite utiliser les outils existants de CusToM. Cela se fait assez bien avec btk : http://biomechanical-toolkit.github.io/docs/Wrapping/Matlab/annotated.html
>    Une fois le c3d généré, vous pouvez alors utiliser les fichiers d'import de CusToM.

Je suis en train d'essayer de convertir mon fichier en c3d avec btk mais il y a très peu d'exemples et je bloque est ce que vous auriez un exemple type ?  J'ai trouvé cette page qui me parait très utile pour définir les fonction à utiliser : http://biomechanical-toolkit.github.io/docs/API/_file_format_supported.html#FileFormatSupported_Acquisition mais c'est du java et je ne trouve pas l'équivalent en matlab.

> 2. Créer une fonction Matlab d'import qui sera spécifique à votre format de données en .txt. Cette devra être placé dans le dossier Functions/DataImport/InputDataImport pour ensuite être directement sélectionné dans l'interface graphique.
>    Cette nouvelle fonction doit contenir les mêmes entrées/sorties que la fonction C3dProcessedData.

Mais ce n'est pas ce qu'est censé faire la fonction MathProcessedData ? En entrée récupérer un ExeprimentalData.mat et ressortir des données suivantes (real_markers, nb_frame, Firstframe, Lastframe, f, list_missing_markers_in_c3d).

**Comment by anmuller** [comment]
Voici quelques lignes pour créer un c3d à l'aide de btk :
` an % Analog channel number`
`frame_number % Number of markers frame`
`r % Number of analog sample per video frame`
`% Create btk file`
`acq = btkNewAcquisition(0,frame_number,an,r);`
`btkSetFrequency(acq,fq); % Set the frequency`
`% Add a marker data`
`btkAppendPoint(acq,'marker','C7',C7_data);`
`btkWriteAcquisition(acq,'c3dname.c3d');`
`btkCloseAcquisition(acq)`

Oui effectivement la fonction MatProcessedData doit bien faire ce que vous dites. A la vue de votre erreur, cela semble être le format de ExperimentalData.MarkerPositions qui ne doit pas être correct. Cela doit être un type struct avec les champs suivants : name (chaîne de caractères), position_c3d (array nb_frame x 3), time (array nb_frame x 1). Chaque élément étant associé à un marqueur.
