### ISSUE TITLE
Comment on README.md

### ISSUE THREAD

**Issue by modenaxe** [anmuller/CusToM#12]
Hello,

 I was exploring CusToM after I reviewed the JOSS paper a while ago and I have noticed this sentence in the README: 

> OpenSim is a freely available software but main algorithms source codes are not available. 

I just wanted to point out - for the sake of accuracy of the README - that it is actually not the case: OpenSim makes all its source code available at https://github.com/opensim-org, even the Java code for the graphical user interface. 

Best regards,

Luca

**Comment by cpontonn** [comment]
Hi Luca, thanks to point this out. We will add the source code link within the readme file, sure !
