### ISSUE TITLE
GenerateAnimate throws error in excution

### ISSUE THREAD

**Issue by modenaxe** [anmuller/CusToM#2]
Executing 'GenerateAnimate.mlapp' Matlab throws the following error:

Error using exist
The first input to exist must be a string scalar or character vector.

Error in GenerateAnimate/ActuateFilename (line 52)
            if exist([app.AnimateParameters.filename(1:end-4) '/ExperimentalData.mat'],'file')

Error in GenerateAnimate/startupFcn (line 135)
            app.ActuateFilename;

Error in GenerateAnimate (line 571)
            runStartupFcn(app, @startupFcn)

**Comment by anmuller** [comment]
I think your current folder is not the folder where the c3d is
