### ISSUE TITLE
[joss-review] How are c3d files loaded?

### ISSUE THREAD

**Issue by modenaxe** [anmuller/CusToM#3]
Hi @anmuller the documentation is a bit vague about how to load c3d files i.e. apparently they are read if 'in the current folder'. Is that Matlab current working folder? If I copy c3d files on that, and then launch the Analyse GUI, it doesn't seem to read them though, and there is no other obvious way of specifying a folder. I have tried few options and even wondered if it might be due to a lag in the GUI, as in my machine I have noticed it's a bit slow at updating.

**Comment by anmuller** [comment]
Hi @modenaxe. Yes it is the Matlab current folder, that specifies where the c3d files are.  You can refer to the video posted in #4.
