### ISSUE TITLE
[joss-review] Are examples running?

### ISSUE THREAD

**Issue by modenaxe** [anmuller/CusToM#4]
Hi @anmuller , could you double check if you can run the provided examples without errors? When I start the provided GUIs, load the parameters from the examples folder and then press the 'run' button,  Matlab is always complaining and not running the analyses or the visualization.  
I can post a more systematic description of the errors if you ensure that the examples are functional in the first place. Thank you!

**Comment by anmuller** [comment]
Hi @modenaxe, I was just testing the examples and they are funtional. If you are interesting, we created a very quick video of the use of an example :
https://drive.google.com/file/d/1_zpWBwQ-S9pBaHbCBJj0qKMDQoVt02PC/view
In the video, all the CusToM folders were added in the path but you have just to add the Functions folders as detailed previously.
I think this video could answer some of your questions. Thank you for the time spent
