### ISSUE TITLE
probleme generating MVNX model

### ISSUE THREAD

**Issue by caromartin** [anmuller/CusToM#6]
![Error 1](https://user-images.githubusercontent.com/59091775/71261789-90a68c80-233e-11ea-8564-212e748e1033.JPG)
![Error 2](https://user-images.githubusercontent.com/59091775/71261802-9308e680-233e-11ea-9809-0082facfe867.JPG)
Error when using Analysis and then Options for external force prediction
Error Line 34 in MVNXModelGeneration.m because line 29 seems to be executed but not well. Problem with cellfun
Can you help me please ?
Thanks 
Caroline

**Comment by bniay** [comment]
Hello,

I have a similar problem. The mvnx version used to generate the model is designed with mvnx files for the version 3 of mvn. However, the new version of the mvn software is 4 and the tree structure obtained when loading a mvnx file in Matlab does not have the 'joint' field anymore .
Regards
Benjamin

**Comment by anmuller** [comment]
Hello @caromartin,
If you're using the example available in the toolbox, it is weird because this function was particularly verified with this mvnx file. 
I'll do some more research and get back to you as soon as possible.
Antoine

**Comment by anmuller** [comment]
Hello @bniay,
Actually, the current functions available in CusToM are only designed with mvnx files generated with the version 3. However, you can still use the latest version of MVN software by selecting the version 3 in the export options. In addition, you must selected the items that will be included in the mvnx file (also in the export options), the item "Joint Angle" has to be checked.
Antoine

**Comment by Ipuch** [comment]
@caromartin it might come from your strsplit.m function. Could you open it to verify if it's good ?
