### ISSUE TITLE
Peak after muscle activation

### ISSUE THREAD

**Issue by liuzehao1026** [anmuller/CusToM#7]
I downloaded and used CusTom-master on Github. The first is when performing the Sidestep muscle simulation, there were three peaks of muscle activation that were not displayed. we adjusted the y-axis range to 200, there were still no peaks value in GluteusMaximus2、RectusFemoris and GluteusMaximus1 muscles. Second, soleus muscle activation rate was small. And the last is when I performed the second time, soleus muscle activation was different. Thank you very much for your help

**Comment by Ipuch** [comment]
Hi, 

First, thank you for using CusToM.

To answer your first question. Muscle forces are evaluated as a product of the activation a and the maximal isometric force F0: 
F=F0*a

So in percentage, the values of a (muscle activation) may range from 0 to 100 but not over 100. But muscle forces may have value over 100. You can check the values in MuscleForcesComputationResults.MuscleForces.

However, it is strange that you got different results in the same simulation. Please check if your structure AnalysisParameters and ModelParameters were the same. Otherwise, could you provide us, your .mat so that we can verify on it?

Kind regards,
Pierre

**Comment by liuzehao1026** [comment]
Hi, I re-run Sidestep's muscle simulation. How can I modify the program so that the muscle activation rate in the image is less than 100 and shows a peak? I will provide you with MuscleForcesComputationResults.MuscleForces.mat and AnalysisParameters.mat and ModelParameters.mat files in the attachment.Thank you very much for your help



------------------ 原始邮件 ------------------
发件人:&nbsp;"Ipuch"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 凌晨2:00
收件人:&nbsp;"anmuller/CusToM"<CusToM@noreply.github.com&gt;;
抄送:&nbsp;"1036759693"<1036759693@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anmuller/CusToM] Peak after muscle activation (#7)




Hi,
 
First, thank you for using CusToM.
 
To answer your first question. Muscle forces are evaluated as a product of the activation a and the maximal isometric force F0:
 F=F0*a
 
So in percentage, the values of a (muscle activation) may range from 0 to 100 but not over 100. But muscle forces may have value over 100. You can check the values in MuscleForcesComputationResults.MuscleForces.
 
However, it is strange that you got different results in the same simulation. Please check if your structure AnalysisParameters and ModelParameters were the same. Otherwise, could you provide us, your .mat so that we can verify on it?
 
Kind regards,
 Pierre

**Comment by liuzehao1026** [comment]
Hi, I re-run Sidestep's muscle simulation. How can I modify the program so that the muscle activation rate in the image is less than 100 and shows a peak? I will provide you with MuscleForcesComputationResults.MuscleForces.mat and AnalysisParameters.mat and ModelParameters.mat files in the attachment.Thank you very much for your help



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ipuch"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 凌晨2:00
收件人:&nbsp;"anmuller/CusToM"<CusToM@noreply.github.com&gt;;
抄送:&nbsp;"1036759693"<1036759693@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anmuller/CusToM] Peak after muscle activation (#7)




Hi,
 
First, thank you for using CusToM.
 
To answer your first question. Muscle forces are evaluated as a product of the activation a and the maximal isometric force F0:
 F=F0*a
 
So in percentage, the values of a (muscle activation) may range from 0 to 100 but not over 100. But muscle forces may have value over 100. You can check the values in MuscleForcesComputationResults.MuscleForces.
 
However, it is strange that you got different results in the same simulation. Please check if your structure AnalysisParameters and ModelParameters were the same. Otherwise, could you provide us, your .mat so that we can verify on it?
 
Kind regards,
 Pierre

**Comment by Ipuch** [comment]
The way muscle forces are calculated, is the main reason why the muscle activation is saturated. Few options are possible to get the rate of activation lower.

The completed solution would be to implement more sophisticated muscle force calculation with force-length and force-velocity relationships.

The easy solution would be to modify artificially the maximal isometric force of the muscle in the function LegMuscle.m

This scaling should be done precautionously according to the litterature, and you may have to multiply all maximal isometric forces by the same coefficient.

By the way, could you tell me why are you interested in muscle peak forces?

**Comment by liuzehao1026** [comment]
In side steps study, we see the muscle activation was over 100% a period of time. So we didn’t known what time was the max muscle activation in the movement. We want know jump, running in the difference condition. So we want know what period of time in the movement and percentage value.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ipuch"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月31日(星期五) 凌晨2:02
收件人:&nbsp;"anmuller/CusToM"<CusToM@noreply.github.com&gt;;
抄送:&nbsp;"1036759693"<1036759693@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anmuller/CusToM] Peak after muscle activation (#7)




The way muscle forces are calculated, is the main reason why the muscle activation is saturated. Few options are possible to get the rate of activation lower.
 
The completed solution would be to implement more sophisticated muscle force calculation with force-length and force-velocity relationships.
 
The easy solution would be to modify artificially the maximal isometric force of the muscle in the function LegMuscle.m
 
This scaling should be done precautionously according to the litterature, and you may have to multiply all maximal isometric forces by the same coefficient.
 
By the way, could you tell me why are you interested in muscle peak forces?

**Comment by liuzehao1026** [comment]
Could you please explain where I should be in legmuscle.m and what modifications I should make.Thank you very much for your help




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ipuch"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月31日(星期五) 凌晨2:02
收件人:&nbsp;"anmuller/CusToM"<CusToM@noreply.github.com&gt;;
抄送:&nbsp;"1036759693"<1036759693@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anmuller/CusToM] Peak after muscle activation (#7)




The way muscle forces are calculated, is the main reason why the muscle activation is saturated. Few options are possible to get the rate of activation lower.
 
The completed solution would be to implement more sophisticated muscle force calculation with force-length and force-velocity relationships.
 
The easy solution would be to modify artificially the maximal isometric force of the muscle in the function LegMuscle.m
 
This scaling should be done precautionously according to the litterature, and you may have to multiply all maximal isometric forces by the same coefficient.
 
By the way, could you tell me why are you interested in muscle peak forces?

**Comment by Ipuch** [comment]
I highlighted the fields you should modify, in the script. It correspond to the maximal isometric forces denoted as f0 below in the script.  I only selected a sample of the whole muscles set, but each maximal isometric forces should be modify. 
![image](https://user-images.githubusercontent.com/40755537/73610022-79acb880-45d3-11ea-9573-1580296950d9.png)

Good luck !

**Comment by liuzehao1026** [comment]
Very grateful for your help. I have successfully solved the problem. Again, I want to ask you what the next four parameters of the tag field represent







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ipuch"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 晚上10:51
收件人:&nbsp;"anmuller/CusToM"<CusToM@noreply.github.com&gt;;
抄送:&nbsp;"1036759693"<1036759693@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anmuller/CusToM] Peak after muscle activation (#7)




I highlighted the fields you should modify, in the script. It correspond to the maximal isometric forces denoted as f0 below in the script.  I only selected a sample of the whole muscles set, but each maximal isometric forces should be modify.
 
 
Good luck !

**Comment by Ipuch** [comment]
I'm glad to know that it helped to solve your problem. The next four parameters are not currently used in the muscle force estimation, but they may be used for computation in a future release.

- f0 states for maximal isometric force (currently used)
- l0 states for optimal fiber length (not used yet)
- Kt states for tendon stiffness (not used yet)
- ls states for tendon slack length (not used yet)
- alpha0 states for pennation angle at optimal fiber length (not used yet)
- path states for the list of via points that define the line of action of the muscle. (currently used)

Regards,

Pierre
