### ISSUE TITLE
Cannot run CusTom in Mac~

### ISSUE THREAD

**Issue by curcify** [anmuller/CusToM#8]
Hi~
My MacOS was 10.15 Catalina. After that my btk functions (e.g. btkReadAcquisition) were identified as malware by my computer. After I manually bypassed the MacOS malware check, my MATLAB (version R2019b) will crash down every time when I tried to run the bypassed function. MATLAB showed the following message when it crashed down.  So cannot run CusTom in Mac.

**Comment by Ipuch** [comment]
Hi,

Thank you, for asking this question. We've just added a tutorial to recompile btk files on MacOS.
Please check the [pdf](https://github.com/anmuller/CusToM/blob/Dev_master/Docs/btk_files_installation_MacOS.pdf), and let us know if it works after.

Regards,

Pierre.

**Comment by curcify** [comment]
Thank for your respond.
Please see attachment.
All the best
           ilin


----------------------------------------------------------
I-Lin Wang[1513773635547_my_orcid_qrcode_s.png]

https://orcid.org/0000-0002-6234-3768
ilin.wang@hotmail.com<mailto:ilin.wang@hotmail.com>  +886 912-223-845

Hope, Love, Peace, Happy

-----------------------------------------------------------


________________________________
寄件者: Ipuch <notifications@github.com>
寄件日期: 2020年3月13日 下午 10:03
收件者: anmuller/CusToM <CusToM@noreply.github.com>
副本: curcify <ilin.wang@hotmail.com>; Author <author@noreply.github.com>
主旨: Re: [anmuller/CusToM] Cannot run CusTom in Mac~ (#8)


Hi,

Thank you, for asking this question. We've just added a tutorial to recompile btk files on MacOS.
Please check the pdf<https://github.com/anmuller/CusToM/blob/Dev_master/Docs/btk_files_installation_MacOS.pdf>, and let us know if it works after.

Regards,

Pierre.

**Comment by curcify** [comment]
Hi how to fix two line in Cmake
Call Stack (most recent call first):
CMakeLists.txt:103 (INCLUDE)
This warning is for project developers. Use -Wno-dev to suppress it.


CMake Error at Wrapping/Matlab/CMakeLists.txt:53 (MESSAGE):
ERROR: Matlab was not founddd!

thank you.
             ilin


----------------------------------------------------------
I-Lin Wang[1513773635547_my_orcid_qrcode_s.png]

https://orcid.org/0000-0002-6234-3768
ilin.wang@hotmail.com<mailto:ilin.wang@hotmail.com>  +886 912-223-845

Hope, Love, Peace, Happy

-----------------------------------------------------------


________________________________
寄件者: Ipuch <notifications@github.com>
寄件日期: 2020年3月13日 下午 10:03
收件者: anmuller/CusToM <CusToM@noreply.github.com>
副本: curcify <ilin.wang@hotmail.com>; Author <author@noreply.github.com>
主旨: Re: [anmuller/CusToM] Cannot run CusTom in Mac~ (#8)


Hi,

Thank you, for asking this question. We've just added a tutorial to recompile btk files on MacOS.
Please check the pdf<https://github.com/anmuller/CusToM/blob/Dev_master/Docs/btk_files_installation_MacOS.pdf>, and let us know if it works after.

Regards,

Pierre.

**Comment by paulinemorin** [comment]
Hi I had this error too ! You have to fill in the path to Matlab (where the application is installed).

**Comment by curcify** [comment]
Yes, it can work.
Thank you.


----------------------------------------------------------
I-Lin Wang[1513773635547_my_orcid_qrcode_s.png]

https://orcid.org/0000-0002-6234-3768
ilin.wang@hotmail.com<mailto:ilin.wang@hotmail.com>  +886 912-223-845

Hope, Love, Peace, Happy

-----------------------------------------------------------


________________________________
寄件者: paulinemorin <notifications@github.com>
寄件日期: 2020年3月18日 上午 02:04
收件者: anmuller/CusToM <CusToM@noreply.github.com>
副本: curcify <ilin.wang@hotmail.com>; Author <author@noreply.github.com>
主旨: Re: [anmuller/CusToM] Cannot run CusTom in Mac~ (#8)


Hi I had this error too ! You have to fill in the path to Matlab (where the application is installed).
