### ISSUE TITLE
Three Axes of the Lower Limb Joint

### ISSUE THREAD

**Issue by zhangkeke95** [anmuller/CusToM#9]
Sorry to bother you. How can I set the lower limb joint like the upper limb joint in Tutorial # 2 to have three rotation angles in Biomechanical Model, OsteoArticular Model. Looking forward  to your reply. Thank you very much.

**Comment by cpontonn** [comment]
Hi, thank you for using custom ! You are not bothering us🙂. Can you be a bit More explicit about your issue ? The lower limb is composed of several joints, i assume you are talking about the hip ? It is already set as a 3 dofs rotational joint in the Classic « leg » model, but the toolbox is decomposing it in 3 independent rotations (hip_J1, ...)
Hope it helps

**Comment by zhangkeke95** [comment]
Thank you for helping me solve the problem and sorry to bother you again.
Can you help me with the next problem? In the attached picture, I want to
get three rotation angles of anklem, knee and hip joints. Such as, Rhip_J1,
Rhip_J2 and Rhip_J3 which exists or not. If J3 exists,  how should I set it
up.Moreover,how to set the three rotation angle of knee and ankle？In
addition, which of J1 and J2，J3 is Flexion Extension，inside and outside
rotation or Inside and outside the flip ？Thank you very much and hope to
hear from you soon.

Charles Pontonnier <notifications@github.com> 于2020年3月29日周日 上午3:37写道：

**Comment by zhangkeke95** [comment]
Sorry to bother you again. How can I use this “but the toolbox is
decomposing it in 3 independent rotations ( hip_J1, ... )”. Thank you very
much and hope to hear from you soon.

张可可 <zhkeke95@gmail.com> 于2020年3月29日周日 下午8:37写道：

**Comment by cpontonn** [comment]
Hi, when creating your model, you can use the leg_ball_joint model that allows 3 rotations per joint (hip, knee, ankle). The order of rotation  for each of these joints is supposed to be zxy, corresponding to flexion/extension, adduction/abduction, internal/external rotation. BR

**Comment by zhangkeke95** [comment]
Follow your instructions，I used leg_ball_joint to build the model in
Biomechanical Model.In the OsteoArticular Model, I got J1 and J2 of
anklem，knee and hip, that is to say,flexion/extension,
adduction/abduction.And how to get  the J3 of internal/external
rotation？Thank you very much.
[image: 7ffff5acb0e0eba31bed2c9038f99f3.jpg]


Charles Pontonnier <notifications@github.com> 于2020年3月30日周一 上午3:56写道：

**Comment by Ipuch** [comment]
Hi Zhangkeke95,

![image](https://user-images.githubusercontent.com/40755537/77889876-de506080-726e-11ea-8724-453f24a3d13e.png)

I uploaded a screenshot from a (Pelvis+A leg with 3 DoFs with each joints) : Hip, Knee, Ankle.
In CusToM, mechanical joints are defined as hinges (joint of type 1) or as sliders (joint of type 2). So to get 3 DoFs at joints, virtual solids are added without any mass properties. ex: in the case of the hip we have two virtual solids RHip_J1 and RHip_J2. These two solids have each a hinge as a DoF. If we get a look at "OsteoArticular.a" field, we can check the axes of rotations: RHip_J1 [0;0;1] is equivalent to z and RHip_J1 [1;0;0] is equivalent to x. The last DoF is done about the y-axis [0;0;1], with the row RThigh, which is a real solid. If you check the fields ".c" , ".m"  and ".I", you can see there is non-zero inertial parameters. 

Another clue can be found in the field ".b", This field is the location of the solid in the parent solid. For RHip_J1 the value is not zero but for RHip_J2 and RThigh, the value is set at zero, meaning there is a unique point of concurrence for the three hinges. So RHip_J1, RHip_J2, RThigh is equivalent to a ball joint.

This analysis of the Hip joint can be generalized to the other joints for the knee and the ankle. Let us know if it is clear for you.

Regards,

Pierre

**Comment by zhangkeke95** [comment]
Sorry to bother you again. I selected ChgtDirection04. C3d in the
SideStep_Processed folder. The operation of Tutorial # 2 is carried out,
and the final result is output into a picture. May I ask if the result of
this picture is correct. Thank you very much and hope to hear from
your reply soon.
[image: 3eb5dd8de06be4a1157f8e3552c2585.png]


Ipuch <notifications@github.com> 于2020年3月30日周一 下午4:29写道：

**Comment by Ipuch** [comment]
Unfortunately your picture has not been loaded correctly. Please reload it on github.

**Comment by zhangkeke95** [comment]
Sorry to bother you again. I selected ChgtDirection04. C3d in the
SideStep_Processed folder. The operation of Tutorial # 2 is carried out,
and the final result is output into a picture. May I ask if the result of
this picture is correct. Thank you very much and hope to hear from
your reply soon.

Ipuch <notifications@github.com> 于2020年3月31日周二 下午3:49写道：

**Comment by LivetClr** [comment]
Hello @zhangkeke95 , 
This is the picture you should have as final result of Tutorial 2 on SideStep_Processed. Does it match with your own result, or were you talking about an another part of the tutorial?
![result_tutorial2_sidestepprocessed](https://user-images.githubusercontent.com/55194284/84137399-f00f6a80-aa4c-11ea-85d7-a2c17731e839.png)
